spring:
  config:
    activate:
      on-profile: dev
  application:
    name: customers
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@129.146.184.44:1521/FREEPDB1
    username: vs
    password: Oracle1
  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.Oracle12cDialect
        globally_quoted_identifiers: true
server:
  port: 8080
  servlet:
    context-path: /vs-customers/api
logging:
  level:
    com:
      vs:
        customer: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

---
spring:
  config:
    activate:
      on-profile: prod
  application:
    name: customers
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@129.146.184.44:1521/FREEPDB1
    username: vs
    password: Oracle1
  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.Oracle12cDialect
        globally_quoted_identifiers: true
server:
  port: 8080
  servlet:
    context-path: /vs-customers/api
logging:
  level:
    com:
      vs:
        customer: INFO
    org:
      hibernate:
        SQL: INFO
oci:
  tenant:
    config: oci
    region: 
    adb-username-ocid: 
    adb-password-ocid: 
    stream-ocid:
    message-endpoint:
    topic-ocid:
