spring:
  config:
    activate:
      on-profile: dev
  application:
    name: customers
  server:
    port: 8080
  datasource:
    url: jdbc:oracle:thin:@129.146.184.44:1521/FREEPDB1
    username: vs
    password: Oracle1
  jpa:
    database: oracle
    hibernate:
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
      show-sql: true
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
server:
  servlet:
    context-path: /vs-customers/api
jwt:
  secret: visionstays
  validity: 600
  get:
    token:
      uri: /signin
logging:
  level:
    com:
      vs:
        customer: DEBUG
oci:
  tenant:
    config: oci
    region: 
    adb-username-ocid: 
    adb-password-ocid: 
    stream-ocid:
    message-endpoint:
    topic-ocid:

---
spring:
  config:
    activate:
      on-profile: prod
  application:
    name: customers
  server:
    port: 8080
  datasource:
    url: jdbc:oracle:thin:@129.146.184.44:1521/FREEPDB1
    username: vs
    password: Oracle1
  jpa:
    database: oracle
    hibernate:
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
      show-sql: true
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
server:
  servlet:
    context-path: /vs-customers/api
jwt:
  secret: visionstays
  validity: 600
  get:
    token:
      uri: /signin
logging:
  level:
    com:
      vs:
        customer: DEBUG
oci:
  tenant:
    config: oci
    region: 
    adb-username-ocid: 
    adb-password-ocid: 
    stream-ocid: 
    message-endpoint: 
    topic-ocid: 
