-- Drop table if exists
DROP TABLE CUSTOMERS CASCADE CONSTRAINTS;

-- Create customers table
CREATE TABLE CUSTOMERS (
    CUSTOMER_ID VARCHAR2(50) NOT NULL,
    CUSTOMER_NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL,
    PASSWORD VARCHAR2(100) NOT NULL,
    PHONE_NUMBER VARCHAR2(20),
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP,
    CONSTRAINT CUSTOMERS_PK PRIMARY KEY (CUSTOMER_ID),
    CONSTRAINT CUSTOMERS_EMAIL_UK UNIQUE (EMAIL)
); 